# Generated by Django 5.1 on 2024-08-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismo', '0002_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
