# Generated by Django 5.1 on 2024-08-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=9, verbose_name='Zip code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('neighborhood', models.CharField(max_length=30, verbose_name='Neighborhood')),
                ('complement', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complement')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Opening hours')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='core.address', verbose_name='Address')),
                ('specialties', models.ManyToManyField(blank=True, related_name='specialists', to='core.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.specialist', verbose_name='Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp phone number')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.specialist', verbose_name='Specialist')),
            ],
        ),
    ]
