# Generated by Django 5.1 on 2024-08-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autismo.login')),
            ],
        ),
    ]
